### ISSUE TITLE
Вопросы для проверки практики в CSC

### ISSUE THREAD

**Issue by MBkkt** [Grand-OT/AppleShortcuts#1]
https://github.com/Grand-OT/AppleShortcuts/blob/main/0001-Add-to-reading-list-doesn-t-work.patch
Выглядит как то некрасиво, понятно что патч может быть не красивый но выглядит просто как хак чтобы добавилась чтото конкретное

По поиску строки в тексте, есть замечание, там искомый текст не вставляется в поле ввода (по крайне мере на видео с эмулятором), мне кажется достаточно удобно чтобы вставлялось, тогда его можно дописать.

По поводу самого приложения, я бещ понятия что это так как не пользуюсь ios. И у меня вопрос правильно ли я понимаю что эти шортакты можно использовать как шоркаты а не как зайти в приложение и нажать на иконку?

**Comment by Grand-OT** [comment]
Здравствуйте!

1) На самом деле, этот патч для того, чтобы следующий патч имел смысл и работал. Смысл этого патча в том, что заложена основа для команды, но при этом есть проблема, которая мешает работать как нужно при определённых обстоятельствах. Конкретно здесь была проблема в том, что команда не работала при холодном запуске приложения. Возможно, действительно, стоило оставить только общий лог изменений. Ну и сами файлы скорее являются историей изменений и хроникой работы, нежели каким-то продуктом, который нужно установить чтобы приложение лучше работало. 

2) Про текст это действительно недоделка. Связана она с тем, что за поиск и за ввод строки отвечают разные сущности. Поиск просто находит переданную строку, а за чтение строки отвечает UI часть. И для чтения строки в Chromium изначально не предполагалось предварительное её заполнение. Собственно, это та проблема, которая должна была быть решённой прямо следующим шагом, но времени не хватило доделать до конца. 

3) Вообще, сами шорткаты можно использовать из приложения, можно вытаскивать на главный экран. Также можно объединять отдельные команды друг с другом. Например, команду с добавлением ссылок в список для чтения можно было бы использовать вместе с командой, которая вытаскивает URL'ы из какого-нибудь входящего письма, чтобы не забывать просматривать пришедшие ссылки когда-нибудь потом. 

Надеюсь, правильно понял вопросы и смог ответить.

**Comment by MBkkt** [comment]
Ок, спасибо

**Comment by MBkkt** [comment]
1. Не это хорошо, то что оно отдельно. Просто нет ли более правильного способа это починить? Ну например проблему с холодным запуском.
3. Не совсем понял, из приложения хрома? Я имею ввиду что если оно работает из приложения шорткатов или главного экрана то не совсем понятно зачем? Что мешает мне просто сделать закладку с нужной страницей? На андроиде можно добавлять отдельные страницы на рабочий стол, вероятно на том тоже?

**Comment by Grand-OT** [comment]
1. Видимо, я не совсем понял вопрос. Он к содержимому патча относится? Или к самой структуре патчей? Не совсем понимаю, что такое более правильный способ, буду благодарен за пример.
2. Да, здесь можно тоже добавлять шорткаты на рабочий стол (для частых действий, например), можно запускать из самого приложения shortcuts(чтобы главный экран не захламлять), можно вызывать их через Siri.

**Comment by MBkkt** [comment]
Про сам код патча, он в отличие от других выглядит странно. Как будто просто хак чтобы заработало, не выглядит как правильное решение. Я могу ошибаться конечно легко. Но просто такое впечатление произвело когда прочитал

**Comment by Grand-OT** [comment]
Пожалуй, так и есть. На момент написания этой части кода действительно было не всё понятно с тем, как именно это должно быть реализовано. После, в ходе решения возникших проблем, решение было переработано.
